# reproducibility
seed: 42

# model name
model_name: ${model_name}  # used to name the directory in which model's checkpoints will be stored (experiments/model_name/...)
export: False

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy: null
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  val_check_interval: 1.0  # you can specify an int "n" here => validation every "n" steps
  max_epochs: 40
  deterministic: True
  fast_dev_run: False
  precision: 32

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_overall_f1
  mode: max
  patience: 5

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_overall_f1
  mode: max
  verbose: True
  save_top_k: 1
  filename: 'checkpoint-val_f1_{val_overall_f1:.4f}-epoch_{epoch:02d}'
  auto_insert_metric_name: False
