# @package _global_

# reproducibility
seed: 42

# optimization
batch_size: 32
gradient_acc_steps: 1
gradient_clip_value: 1.0
max_epochs: 10

# evaluation and persistence
apply_early_stopping: True
val_check_interval: 1.0
monitor_var: 'val_f1'
monitor_var_mode: 'max'
patience: 5
model_name: 'default_name'  # used to name the directory in which model's checkpoints will be stored (experiments/model_name/...)
save_top_k: 2

# core
gpus: 1
precision: 32
