# @package _group_

# reproducibility
seed: 42

# model name
model_name: ${name}  # used to name the directory in which model's checkpoints will be stored (experiments/model_name/...)

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  gpus: 1
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  val_check_interval: 1.0  # you can specify an int "n" here => validation every "n" steps
  max_epochs: 10
  deterministic: True
  fast_dev_run: False
  precision: 32

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss
  mode: min
  patience: 5

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_f1
  mode: max
  verbose: True
  save_top_k: 2
  filename: 'checkpoint-val_f1_{val_f1:.4f}-epoch_{epoch:02d}'
  auto_insert_metric_name: False
