# @package _group_

_target_: pl_modules.NERModule

# my typical model feature
language_model_name: 'distilbert-base-cased'
lr: 1e-5
weight_decay: 0
lm_fine_tune: True
subtoken_pooling: 'mean'
output_layer: 'sum'
