_target_: pl_modules.NERModule
language_model_name: 'microsoft/Multilingual-MiniLM-L12-H384'
return_words: True
output_layer: 'sum'
# learning hyper-parameters
lr: 2e-4
lm_lr: 1e-5
weight_decay: 0
lm_fine_tune: True
