_target_: models.pl_modules.NERModule

model:
  _target_: models.models.TransformersNER
  language_model: 'roberta-large'
  return_words: True
  layer_pooling_strategy: 'mean'
  fine_tune: True
  dropout: 0.1
  use_viterbi: True

optim_params:
  optimizer: 'radam'
  lr: 2e-4
  lm_lr: 2e-5
  lm_weight_decay: 0.0
  weight_decay: 0
